### ISSUE TITLE
Please make a new release version of this module

### ISSUE THREAD

**Issue by clementbegnaud** [Smile-SA/jahia-cookie-consent#5]
Hi,

I am using this module on one of my project, and noticed the french traduction bug, which was fixed in 2018. Though, no more stable version was released since then, so all we can't get the fix on our projects.

Would you please make a release version?

**Comment by cedfou** [comment]
Hello, 
Could you publish a new release because there are some bugfixing (in the last commits) that we need in our projects? 

Kind regards,

**Comment by spw-dtic** [comment]
Hello,
Could you publish a new release because there are some bugfixing (in the last commits) that we need in our projects?

Kind regards,

**Comment by cdebauche** [comment]
Hello,
Could you publish a new release because there are some bugfixing (in the last commits) that we need in our projects?

Kind regards,

**Comment by cedfou** [comment]
Thanks @marob  for this quick release : 
https://github.com/Smile-SA/jahia-cookie-consent/releases/tag/cookie-consent-1.3 

Problem solved for us, you can close this issue 👍 
PS: good luck for the deploiement on Jahia store
